config/routes.rb
Rails.application.routes.draw do
  get 'tournaments/index'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  get '/players/update_players' => 'players#update_players'
  get '/users/add_pick' => 'users#add_pick', :as => :add_pick
  post '/users/add_pick' => 'users#submit_pick'
  get '/all' => 'home#all_results'
  get '/tourney' => 'tournaments#index', as: :tourney
  post '/tourney/create' => 'tournaments#create', as: :create_tourney
  resources :users

  if Rails.env.development?
    require 'mr_video'
    mount MrVideo::Engine => '/mr_video'
  end
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base

  def self.active
    Tournament.order(start: :desc).first
  end

  def started?
    Date.today >= self.start
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @leaderboard = Golfscrape::Client.new.leaderboard
    @tournament = Tournament.active 
  end

  def create
    #TODO: refactor this into Golfscrape
    @leaderboard = Golfscrape::Client.new.leaderboard
    tournament_details = @leaderboard.tournament
    name_and_date = get_name_and_date(tournament_details.name)

    @tournament = Tournament.create(name:name_and_date[:name],
                      start: name_and_date[:start_date],
                      course_par: tournament_details.par)
    @players = PlayersUpdater.update_players
    render :index
  end


  private

  def get_name_and_date(tournament_description)
    tokens = tournament_description.match(/([\w\s]*)\((\w{3}\s\d*)/i).captures
    {
      name: tokens[0].strip,
      start_date: Date.strptime(tokens[1], '%b %d')
    }
  end
end

app/views/tournaments/index.html.slim
.row
  .small-12.columns
    h3 Tournaments
    .panel
      h5 Current Available Tournament
      p
        strong Name: 
        = @leaderboard.tournament.name
      div
        strong Par: 
        = @leaderboard.tournament.par
      = link_to 'Create Tournament', create_tourney_path, method: :post,
        class: 'button tiny'
    .panel.last
      h5 Last Tournament in DB
      - if @tournament
        p
          strong Name: 
          = @tournament.name
        div
          strong Started:
          =< @tournament.start
        - if @players
          p #{@players[:new]} players added, #{@players[:updated]} updated
      - else
        p
          No current tournament